### ISSUE TITLE
貌似不能导出

### ISSUE THREAD

**Issue by tongstarE** [NotFaceGUI/nikke-balabala#1]
很有意思的小工具。不过测试了一下，换了几个浏览器都无法导出图片。期待后续更新~

**Comment by NotFaceGUI** [comment]
是安卓机吗，安卓上的浏览器貌似不能直接下载base64 你可以先尝试使用电脑导出，手机端正在尝试更好的解决方案

**Comment by NotFaceGUI** [comment]
我提交了一个临时的解决方案。
1.有的安卓浏览器仍然不支持导出图片（如：夸克、百度）为此我添加了一个预览图的功能。如果无法导出图片，可以直接保存预览图，和导出效果一致。
2.使用edge等支持导出的浏览器
